config/routes.rb
Ehonk::Application.routes.draw do
  resources :messages

  resources :blocking_clients

  match '/register' => 'operation#register'
  match '/get_messages' => 'operation#get_messages'
  match '/unregister' => 'operation#unregister'
  match '/search' => 'operation#search'

end

app/models/blocking_client.rb
class BlockingClient < ActiveRecord::Base
  attr_accessible :blocking_client_id, :car_number, :lat, :long
  has_many :messages
end

app/controllers/blocking_clients_controller.rb
class BlockingClientsController < ApplicationController
  # GET /blocking_clients
  # GET /blocking_clients.json
  def index
    @blocking_clients = BlockingClient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blocking_clients }
    end
  end

  # GET /blocking_clients/1
  # GET /blocking_clients/1.json
  def show
    @blocking_client = BlockingClient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blocking_client }
    end
  end

  # GET /blocking_clients/new
  # GET /blocking_clients/new.json
  def new
    @blocking_client = BlockingClient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blocking_client }
    end
  end

  # GET /blocking_clients/1/edit
  def edit
    @blocking_client = BlockingClient.find(params[:id])
  end

  # POST /blocking_clients
  # POST /blocking_clients.json
  def create
    @blocking_client = BlockingClient.new(params[:blocking_client])

    respond_to do |format|
      if @blocking_client.save
        format.html { redirect_to @blocking_client, notice: 'Blocking client was successfully created.' }
        format.json { render json: @blocking_client, status: :created, location: @blocking_client }
      else
        format.html { render action: "new" }
        format.json { render json: @blocking_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blocking_clients/1
  # PUT /blocking_clients/1.json
  def update
    @blocking_client = BlockingClient.find(params[:id])

    respond_to do |format|
      if @blocking_client.update_attributes(params[:blocking_client])
        format.html { redirect_to @blocking_client, notice: 'Blocking client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blocking_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocking_clients/1
  # DELETE /blocking_clients/1.json
  def destroy
    @blocking_client = BlockingClient.find(params[:id])
    @blocking_client.destroy

    respond_to do |format|
      format.html { redirect_to blocking_clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blocking_clients_helper.rb
module BlockingClientsHelper
end

app/views/blocking_clients/_form.html.erb
<%= form_for(@blocking_client) do |f| %>
  <% if @blocking_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blocking_client.errors.count, "error") %> prohibited this blocking_client from being saved:</h2>

      <ul>
      <% @blocking_client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blocking_client_id %><br />
    <%= f.number_field :blocking_client_id %>
  </div>
  <div class="field">
    <%= f.label :car_number %><br />
    <%= f.text_field :car_number %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocking_clients/edit.html.erb
<h1>Editing blocking_client</h1>

<%= render 'form' %>

<%= link_to 'Show', @blocking_client %> |
<%= link_to 'Back', blocking_clients_path %>

app/views/blocking_clients/index.html.erb
<h1>Listing blocking_clients</h1>

<table>
  <tr>
    <th>Blocking client</th>
    <th>Car number</th>
    <th>Lat</th>
    <th>Long</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blocking_clients.each do |blocking_client| %>
  <tr>
    <td><%= blocking_client.blocking_client_id %></td>
    <td><%= blocking_client.car_number %></td>
    <td><%= blocking_client.lat %></td>
    <td><%= blocking_client.long %></td>
    <td><%= link_to 'Show', blocking_client %></td>
    <td><%= link_to 'Edit', edit_blocking_client_path(blocking_client) %></td>
    <td><%= link_to 'Destroy', blocking_client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blocking client', new_blocking_client_path %>

app/views/blocking_clients/new.html.erb
<h1>New blocking_client</h1>

<%= render 'form' %>

<%= link_to 'Back', blocking_clients_path %>

app/views/blocking_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Blocking client:</b>
  <%= @blocking_client.blocking_client_id %>
</p>

<p>
  <b>Car number:</b>
  <%= @blocking_client.car_number %>
</p>

<p>
  <b>Lat:</b>
  <%= @blocking_client.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @blocking_client.long %>
</p>


<%= link_to 'Edit', edit_blocking_client_path(@blocking_client) %> |
<%= link_to 'Back', blocking_clients_path %>